name: Python CI

on:
  push:
    branches:
      - main
      - develop
      - release-*
      - feature-pytest-testbook-integration**
  pull_request:
    branches:
      - main
      - develop
      - release-*
      - feature-pytest-testbook-integration**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.10.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r env/requirements.txt

    # Add any additional commands you need
    - name: Run tests
      run: |
        python -m pytest
        echo "Run your test suite here"
